# docker-compose.yml
services:
  app:
    build: .
    image: todo-app:latest  
    ports:
      - "8000:80" 
    volumes:
      - .:/var/www/html  
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html  
